In [1]:
import numpy as np


In [2]:
def pearson_correlation(matrix):
    # Calculate mean of each column
    column_means = np.mean(matrix, axis=0)
    
    # Subtract the mean from each element
    centered_matrix = matrix - column_means
    
    # Calculate the numerator
    numerator = np.dot(centered_matrix.T, centered_matrix)
    
    # Calculate the denominator
    denominator = np.sqrt(np.sum(centered_matrix**2, axis=0))
    denominator_matrix = np.outer(denominator, denominator)
    
    # Handle division by zero
    denominator_matrix[denominator_matrix == 0] = np.nan
    
    # Calculate the correlation matrix
    correlation_matrix = numerator / denominator_matrix
    
    return correlation_matrix

# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate Pearson correlation coefficient
correlation_matrix = pearson_correlation(matrix)
print(correlation_matrix)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
